import './globals.css';
import { Inter } from 'next/font/google';
import Header from './BurgerMenu';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  // Create the `onClose` handler function
  const handleClose = () => {
    console.log("Menu closed!");
    // Handle additional logic for when the menu is closed if necessary
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Pass the `onClose` function to Header */}
        <Header onClose={handleClose} showMenu={false} isProjectViewRoute={false}/>
        {children}
      </body>
    </html>
  );
}
